---
title: "Predicting Democratic Backsliding: Final Report"
author: "Yousuf"
date: "12/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tufte)
```

```{css, echo=FALSE}
h1, h2, h3 {
  text-align: center;
}
```

<center> Github Repository: "https://github.com/yousufabdelfatah/Predicting-Democratic-Backsliding.git" </center>


## 1. Introduction

The aim of the project is to build a model that can predict democratic backsliding

First we'll go through a brieg background about the issue and the literature on the topic. Then we'll discuss the data sources. Then discuss the analysis and then a discussion of the results. 

## 2. Problem Statement and Background

Much has been made recently of the fact that the global trend towards democracy seems to be reversing and that many countries are experiencing what is known as democratic backsliding. Democratic backsliding, defined as the "state-led debilitation or elimination of the political institutions sustaining an existing democracy," is a catch-all term to describe the various processes by which states move towards more authoritarian forms of governance.[^1] This phenomenon is becoming increasingly common, and the average level of democracy worldwide has slipped to where it was before the year 2000.[^2] In fact, electoral autocracies are now the most common form of government in the world.[^3] The question remains, however: what are the causal factors of democratic backsliding and what indicators can be used to predict whether or not a country will regress farther away from democratic governance? In this analysis I will explore

Atempts to model global instability have shown that []. 

The goal is to build a model that can accurately predict democratic backsliding. The idea is that if the model can accurately predict incidents of democratic backsliding then based on variable importance we can intuit what causes backsliding. 

## 3. Data

Country-year was unit of observation. Country names were standardized using country-converter

### 3.1 Dependent variable

To measure democratic backsliding, information about the level of a country's democracy was pulled from the Polity Project's Polity 5 data set. Measures of democratic backsliding were created by subtracting polity data from the year before. The Polity 5 data set covers all major states over the period 1800-2018 and measures various qualities of democratic and authoritarian governance for each.[^4]  Most importantly for this project, each regime is given a "Polity Score," on a 21 point scale from -10 (hereditary monarchy) to 10 (consolidated democracy). 

Democratic backsliding was calaculate susing year over year difference in the polity score (subtracting from the year before). A negative score meant backsliding. 

### 3.2 Independent Variables
Initial plan was to use social cohesion data- not enough
Instead pulled country-level information on ___ from vdems. The V-Dem index is a "multidimensional and disaggregated data set that reflects the complexity of the concept of democracy as a system of rule".[^5] It provides indices for features of democracy at various levels of abstraction. 

Because the vdems data file was too large to upload to github, I first filtered by year, added decades dumy variables, made the features selection, and then reuploaded that as the file vdem_small. 

I split the v-dem data into 5 "buckets"- civil liberties, civil society, media, access to services, and strife. 


The initial intent of the project was to use economic indicators as their own feature bucket. However, in the data collection phase it became clear that economic indicators had a significant amount of missingness. Instead using economic data to control for different effects of vdem factors by size of population and economy. Treating them as control variables now instead of key independent variables. 
Populatoin Data was sourced from the World Bank and information on GDP and GDP per capita were sourced from gapminder. After 1990, the gapminder data from the world bank, while in the period beforehand it is based on several other source, including Angus maddison.[^6]. Its pre-1990 predictions are not super accurate, however it is far more complete than other available sources and in the interest of maintaing as many observations of backsliding as possible, and because economic indicators were no longer a key feature and instead an identifying characteristic, I felt that mainttaining as many observations as possible was more important.

In order to control for temporal effects I included a decades dummy variable. 

Lagged all the dependent variables.

## 4. Analysis



### 4.1 Classifiers

Naive Bayes:

K Nearest Neighbors: Tuned on number og neighbors

Decision Tree: Tuned on Max depth

Random Forest: Tuned on max depth, number of estimators, and max features

Support Vector Classifier: 

### 4.2 Metrics

Balanced accuracy:




## 5. Results


## 5.1 Discussion of Results




## Works Cited
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bermeo, Nancy. "On Democratic Backsliding." Journal of Democracy 27, no. 1 (2016): 5-19. doi:10.1353/jod.2016.0012.
    
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Coppedge, Michael, John Gerring, Carl Henrik Knutsen, Staffan I. Lindberg, Jan Teorell, David Altman, Michael Bernhard, M. Steven Fish, Adam Glynn, Allen Hicken, Anna L¨uhrmann, Kyle L. Marquardt, Kelly McMann, Pamela Paxton, Daniel Pemstein, Brigitte Seim, Rachel Sigman, Svend-Erik Skaaning, Jeffrey Staton, Steven Wilson, Agnes Cornell, Nazifa Alizada, Lisa Gastaldi, Haakon Gjerløw, Garry Hindle, Nina Ilchenko, Laura Maxwell, Valeriya Mechkova,
   
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lührman, Anna, Seraphine F. Maerz, Sandra Grahn, Nazifa Alizada, Lisa Gastaldi, Sebastian Hellmeier, Garry Hindle and Staffan I. Lindberg. 2020. Autocratization Surges – Resistance Grows. Democracy Report 2020. Varieties of Democracy Institute (V-Dem).
   
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Marshall, Monty G., Ted Robert Gurr. 2020. "Polity5: Political Regime Characteristics and Transitions, 1800-2018. Dataset Users' Manual. Center for Systemic Peace. http://www.systemicpeace.org/inscr/p5manualv2018.pdf"
    
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Mechkova, Valeriya, Anna Lührmann, and Staffan I. Lindberg. "How Much Democratic Backsliding?" Journal of Democracy 28, no. 4 (2017): 162-169. doi:10.1353/jod.2017.0075.




[^1]: Nancy Bermeo. "On Democratic Backsliding." Journal of Democracy 27, no. 1 (2016): 5-19. doi:10.1353/jod.2016.0012.
[^2]: Valeriya Mechkova, Anna Lührmann, and Staffan I. Lindberg. "How Much Democratic Backsliding?" Journal of Democracy 28, no. 4 (2017): 162-169. doi:10.1353/jod.2017.0075.
[^3]: Anna Lührmann et al. Autocratization Surges – Resistance Grows. Democracy Report 2020. Varieties of Democracy Institute (V-Dem).https://www.v-dem.net/media/filer_public/de/39/de39af54-0bc5-4421-89ae-fb20dcc53dba/democracy_report.pdf 
[^4]: Marshall, Monty G., Ted Robert Gurr. 2020. "Polity5: Political Regime Characteristics and Transitions, 1800-2018. Dataset Users' Manual. Center for Systemic Peace. http://www.systemicpeace.org/inscr/p5manualv2018.pdf"
[^5]: Michael Coppedge et al., 2020. ”V-Dem [Country–Year/Country–Date] Dataset v10” Varieties of Democracy (V-Dem) Project. https://doi.org/10.23696/vdemds20.
[^6]: https://www.gapminder.org/data/documentation/gd001/
